package zigzag

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

var result string

func TestConvert(t *testing.T) {
	tests := []struct {
		input string
		rows  int
		want  string
	}{
		{"A", 1, "A"},
		{"PAYPALISHIRING", 4, "PINALSIGYAHRPI"},
		{"PAYPALISHIRING", 5, "PHASIYIRPLIGAN"},
		{"PAYPALISHIRINGRANDOMSTRING", 6, "PRSAIIMTYHNORPSGDIAIRNNLAG"},
		{
			"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth",
			1,
			"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth",
		},
		{
			"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth",
			1000,
			"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth",
		},
		{
			"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth",
			100,
			"caawpmigvhvdotfotveeeeersurhirtrchkalfeleheoswllhewhehnihemsaaoidsniheirrhreeictarttwllcfheseheeigrntvupssvgalharttoeutuegeoihsreeyyonntttdhweflgrhsithhdlwoaotooteahfthftfhvheetwaeocostchdrruitehaaaaeghileltebhhwoprpndodtrnotgadvehotehntnetefhpaiiaoareaettogucesthnsnnrihuwtaemipdaaerprivoevchotlgiodetefiahlretareontnpbhhelnileoouthpofimntsoioravlwrftgeaseeeeanhpnaIvrhroleydtattsiyhnliroaotrtaesbarnoeyriaedgovsbtflhdnbeoeittToildlloaodrvydvpnhgndiaeeosteueldsteoftotevahpcohrrhaeaeonegatnrthnorscsccttcifituenhfetahTrdieoirntgoIestvogwhftkenepaoesiadedanlwistemaedlotreanntparIawdrdarhletdsespotdrhahvocpoaeeeaodiendhrdlgedrnsdfdltdetawioenaidhcfdrrohcoaeiyuottattwlesnhdtewelhtoanemetltohvadosaitbeemcchrtaesdoaeocthheidnvuelweheelalsetrtdeohdnneemirnedoogdonfgWoctrervferttlodfaonahoefitihdwinnrcantutsnoeahtrraBarvtthiehucleesabWzteondutwetiwnnteteafnegaorhnroatrctoiaedlaethfseqlacmieenvmmrietgbaaeegdmurgthtieebbenilofrdeeaiolnestrrtnnaaleowetiuhgtnnhhdansrtsnayamsdeaeatafedoabwcwssreGteekr",
		},
	}

	for _, v := range tests {
		t.Log("Input: ", v.input)
		got := convert(v.input, v.rows)
		assert.Equal(t, v.want, got)
	}
}

func BenchmarkConvertShort(b *testing.B) {
	inputs := []struct {
		input string
		rows  int
	}{
		{"A", 1},
		{"b", 1},
		{"c", 1},
		{"d", 1},
		{"PAYPALISHIRING", 4},
		{"ABC", 2},
		{"PAYPALISHIRING", 5},
		{"ABCDEFGHIJKLMNO", 3},
		{"ABCDEFGHIJKLMNOPQRSTUVWXYZ1234568", 7},
		{"PAYPALISHIRINGRANDOMSTRINGwithalongoverheadandneverending", 16},
		{"PAYPALISHIRINGRANDOMSTRING", 6},
		{"PAYPALISHIRINGRANDOMSTRINGwithnoend", 9},
	}

	l := len(inputs)

	funcs := []struct {
		name string
		f    func(s string, n int) string
	}{
		{"my0msV1", convert},
		{"leet-4ms", convertLeet4ms},
	}

	var res string
	for _, fun := range funcs {
		b.Run(fun.name, func(b *testing.B) {
			b.ReportAllocs()
			b.ResetTimer()
			for k := 0; k < b.N; k++ {
				res = fun.f(inputs[k%l].input, inputs[k%l].rows)
			}

		})
	}

	result = res
}

func BenchmarkConvertLong(b *testing.B) {
	inputs := []struct {
		input string
		rows  int
	}{
		{
			"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth",
			1,
		},
		{"PAYPALISHIRINGRANDOMSTRING", 6},
		{
			"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth",
			1000,
		},
		{"PAYPALISHIRINGRANDOMSTRINGwithnoend", 9},
		{
			"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth",
			100,
		},
		{
			"abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz",
			500,
		},
		{
			"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth",
			1000,
		},
		{
			"civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth",
			200,
		},
		{
			"abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz",
			800,
		},
		{
			"abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz",
			750,
		},
		{
			"abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz1234567890abcdefghijklomnpqrstuvwxyz",
			70,
		},
	}

	l := len(inputs)

	funcs := []struct {
		name string
		f    func(s string, n int) string
	}{
		{"my0msV1", convert},
		{"leet-4ms", convertLeet4ms},
	}

	var res string
	for _, fun := range funcs {
		b.Run(fun.name, func(b *testing.B) {
			b.ReportAllocs()
			b.ResetTimer()
			for k := 0; k < b.N; k++ {
				res = fun.f(inputs[k%l].input, inputs[k%l].rows)
			}

		})
	}

	result = res
}
